<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	/**
	 * Views
	 */
	///\vendor\yongtiger\yii2-cropper-avatar\src\views\index.php
	'Avatar' => '头像',
	'Change the avatar' => '上传头像',
	'Change Avatar' => '上传头像',
	'Local upload' => '本地上传',
	'Done' => '完成',
	'Rotate -90 degrees' => '逆时针旋转90度',
	'Rotate Left' => '左旋',
	'Rotate 90 degrees' => '顺时针旋转90度',
	'Rotate Right' => '右旋',
	'deg' => '度',

];
